# Generated by Django 3.2.10 on 2023-09-27 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100, verbose_name='Campaign Name')),
                ('candidates', models.TextField(help_text='Enter candidates separated by commas', verbose_name='Candidates List')),
                ('num_seats', models.PositiveIntegerField(verbose_name='Number of Seats')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.TextField(help_text='Enter candidates separated by commas', verbose_name='Preference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('campaign_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campaign', verbose_name='Campaign')),
            ],
        ),
    ]
